import { AboutSlint, Button, StandardButton, VerticalBox, LineEdit, HorizontalBox, ListView, ScrollView, StandardButton } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback draw_person;
    callback restart;

    in-out property <string> status;
    in-out property <string> list;
    in-out property <string> listFile;
    in-out property <string> winner;

    width: 600px;
    preferred-height: 1000px;
    VerticalLayout {
        alignment: start;
        Text {
            text: list;
            font-size: 16px;
            horizontal-alignment: center;
        }
    }
    VerticalLayout {
        alignment: end;
        Text {
            text: status;
            font-size: 16px;
            horizontal-alignment: center;
        }
        Text {
            text: winner;
            font-size: 24px;
            horizontal-alignment: center;
        }
        Button {
            text: "Wylosuj";
            width: parent.width / 2;
            x: parent.width / 4;
            clicked => { draw_person() }
        }
        HorizontalBox {
            alignment: stretch;
            Text {
                text: "plik listy";
                width: parent.width / 3;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
            LineEdit {
                text: listFile;
                font-size: 12px;
                width: parent.width / 3;
            }
        }

        popup := PopupWindow {
            Rectangle { height:100%; width: 100%; background: yellow; }
            x: parent.width / 3;
            y: parent.height / 2;
            width: parent.width / 3;
            Dialog {
                Text {
                    text: "Przeładować listę?";
                    color: red;
                }
                StandardButton {
                    kind: ok;
                    clicked => { restart() }
                }
                StandardButton { kind: cancel; }
            }
        }

        Button {
            text: "Przeładuj listę";
            width: parent.width / 2;
            x: parent.width / 4;
            clicked => { popup.show() }
        }
    }
}
