import {
    AboutSlint,
    Button,
    StandardButton,
    VerticalBox,
    LineEdit,
    HorizontalBox,
    ListView,
    ScrollView,
    StandardButton,
    Palette, TextEdit
} from "std-widgets.slint";

export component PasteWindow inherits Window {
    title: "Loteria Paste";
    out property <string> names;

    callback names_ready;

    min-width: 400px;
    min-height: 400px;

    Rectangle {
        vertical-stretch: 0;
        background: Palette.control-background;
        border-color: Palette.control-foreground;
        VerticalBox {
            alignment: stretch;
            padding: 15px;
            TextEdit {
                text: names;
                preferred-height: 400px;
                edited(text) => {
                    names = text;
                }
            }
            Button {
                height: 100px;
                text: "Załaduj";
                clicked => {
                    names_ready();
                }
            }
        }
    }
    
}

export component AppWindow inherits Window {
    title: "Loteria";

    callback draw_person;
    callback restart;

    in-out property <string> status;
    in-out property <string> list;
    in-out property <string> winner;

    min-width: 500px;
    min-height: 500px;

    Rectangle {
        background: Palette.control-background;
        VerticalBox {
            ScrollView {
                vertical-scrollbar-policy: always-on;
                viewport-height: 2000px;
                Text {
                    y: 0;
                    text: list;
                    font-size: 16px;
                    horizontal-alignment: center;
                    vertical-alignment: top;
                }
            }
            VerticalLayout {
                alignment: end;
                VerticalBox {
                    Text {
                        text: status;
                        font-size: 16px;
                        horizontal-alignment: center;
                        color: Palette.control-foreground;
                    }
                    Text {
                        text: winner;
                        font-size: 24px;
                        horizontal-alignment: center;
                        color: Palette.control-foreground;
                    }
                }
                Button {
                    text: "Wylosuj";
                    clicked => { draw_person() }
                }
            }
        }
    }
}
